#!/bin/bash

set -e

# Usage:
# bareos-volumes-maintenance /var/lib/bareos/storage-local

VOLUMES_PATH="$1"

prune_all() {
  echo 'Pruning volumes...'

  FILES=`ls -1 "${VOLUMES_PATH}" | grep -E -v '\.bsr$'`

  for VOLUME in $FILES; do
    bconsole <<< "prune volume=${VOLUME} yes" > /dev/null
  done
}

delete_purged() {
  echo 'Deleting purged volumes from catalog...'

  PURGED=`echo 'list volumes' | bconsole | grep 'Purged' | awk '{ print $4 }'`

  echo "Purged volumes: `echo ${PURGED} | xargs`"

  for VOLUME in $PURGED; do
    bconsole <<< "delete volume=${VOLUME} yes" > /dev/null
  done
}

delete_obsolete() {
  echo 'Deleting obsolete volume files...'

  FILES=`ls -1 "${VOLUMES_PATH}" | grep -E -v '\.bsr$'`

  for VOLUME in $FILES; do
    if bconsole <<< "list volume=${VOLUME}" | grep -q 'No results to list'; then
      OBSOLETE=`printf "${OBSOLETE}\n${VOLUME}"`
    fi
  done

  echo "Obsolete volume files: `echo ${OBSOLETE} | xargs`"
 
  echo "${OBSOLETE}" | xargs -I '{}' rm -f "${VOLUMES_PATH}/{}"
}

prune_all
delete_purged
delete_obsolete
